"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
console_title_template = "{{.Folder}} | {{.Shell}} ~ {{.ShellVersion}}"
final_space = true
version = 2

[[blocks]]
alignment = "left"
type = "prompt"
newline = true
  
  [[blocks.segments]]
  type = "text"
  style = "plain"
  foreground = "white"
  template = "╭─ "

  [[blocks.segments]]
  type = "text"
  style = "plain"
  foreground = "#d50000"
  template = "◓ "

  [[blocks.segments]]
  type = "session"
  style = "diamond"
  leading_diamond = ""
  trailing_diamond = ""
  background = "#1e88e5"
  template = "{{ .UserName }}"

  [[blocks.segments]]
  type = "path"
  style = "powerline"
  background = "#ab47bc"
  powerline_symbol = ""

    [blocks.segments.properties]
    style = "unique"

  [[blocks.segments]]
  type = "git"
  style = "plain"
  foreground = "green"
  template = " {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} \uF044 {{ .Working.String }}{{ end }}{{ if and (.Staging.Changed) (.Working.Changed) }} |{{ end }}{{ if .Staging.Changed }} \uF046 {{ .Staging.String }}{{ end }}"

    [blocks.segments.properties]
    fetch_status = true

[[blocks]]
type = "prompt"
alignment = "right"

  [[blocks.segments]]
  type = "terraform"
  style = "plain"
  template = "Terraform {{ .Version }}"

    [blocks.segments.properties]
    fetch_version = true

  [[blocks.segments]]
  type = "az"
  style = "powerline"
  template = " {{ if .UserName }}  {{ .Name }} {{ end }}"

  [[blocks.segments]]
  type = "status"
  style = "plain"
  template = "{{ if eq .Code 0 }}\uf00c{{ else }}\uf071{{ end }} "

    [blocks.segments.properties]
    always_enabled = true

  [[blocks.segments]]
  type = "executiontime"
  style = "plain"
  template = " {{ .FormattedMs }} "

    [blocks.segments.properties]
    threshold = 1
    style = "austin"

  [[blocks.segments]]
  type = "time"
  style = "plain"
  foreground = "#007ACC"
  template = " {{ .CurrentDate | date .Format }} "

    [blocks.segments.properties]
    time_format = "15:04:05"

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

  [[blocks.segments]]
  type = "text"
  style = "plain"
  foreground = "white"
  template = "╰─❯"